### ISSUE TITLE
Default android template fail at runtime.

### ISSUE THREAD

**Issue by Donaut** [tlgkccampbell/ultraviolet#135] opened 2020-09-18 16:59 UTC
![ErrorAndroid](https://user-images.githubusercontent.com/30203762/93623699-67a34d00-f9df-11ea-892f-90b77cbeec21.png)

**Device:**
Xiaomi Redmi Note 7 -> Android 9.0 - API 28

**Reproduce the error:**
1. Create a project that includes the Android Template
2. Start the project

**Comment by tlgkccampbell** [comment] 2020-09-19 23:27
Is a stack trace included in the exception details? It looks like some GLSL is failing to compile but it's hard to tell which shader it might be.

**Comment by tlgkccampbell** [comment] 2020-09-20 00:18
Nevermind, I was able to reproduce on my own Android device. I'll investigate and get this fixed.

**Comment by tlgkccampbell** [comment] 2020-09-20 15:29
A fix has been merged to `develop` and will be part of the next release.

**Closed by tlgkccampbell** 2020-09-20 15:29 UTC
